name: 'Auto Approve PR'
description: 'Automatically approve pull requests from skipped branches'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'GitHub secret token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'