name: Auto Approve Pull Request
on:
  pull_request:
    branches:
      - master
      - 'skip-*'
jobs:
  build:
    name: Approve PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch out code
        uses: njeri-ngigi/Auto-Approve-Pull-Requests@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          BRANCH_PREFIX: "skip-*"
          PULL_REQUEST_BRANCH: "master"
